import React, { createContext, useContext, useState, useEffect } from 'react';

interface LanguageContextType {
  language: 'en' | 'ar';
  setLanguage: (lang: 'en' | 'ar') => void;
  t: (key: string) => string;
  isRTL: boolean;
}

const translations = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.myItems': 'My Items',
    'nav.offers': 'Trade Offers',
    'nav.messages': 'Messages',
    'nav.profile': 'Profile',
    'nav.admin': 'Admin',
    'nav.login': 'Login',
    'nav.register': 'Register',
    'nav.logout': 'Logout',

    // Auth
    'auth.welcome': 'Welcome to Tebadel',
    'auth.subtitle': 'Trade items with or without money',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.phone': 'Phone Number',
    'auth.phoneHolder': 'Enter phone number',
    'auth.passwordHandler': 'Enter password',
    'auth.name': 'Full Name',
    'auth.firstName': 'First Name',
    'auth.lastName': 'Last Name',
    'auth.loginButton': 'Sign In',
    'auth.loginerror': 'Login Failed',
    'auth.registerButton': 'Create Account',
    'auth.switchToRegister': "Don't have an account? Sign up",
    'auth.switchToLogin': 'Already have an account? Sign in',
    'auth.firstNameHolder': 'Enter your first name',
    'auth.lastNameHolder': 'Enter your last name',
    'auth.passwordHolder': 'Enter your password',
    'auth.registerSuccess': 'Account created successfully!',
    'auth.registerError': 'Registration failed. Please try again.',

    // Landing Page
    'landing.badge': 'The Future of Exchange',
    'landing.heroTitle': 'Trade Items,',
    'landing.heroTitleHighlight': ' with Optional Money Difference',
    'landing.heroSubtitle': 'The modern barter platform: trade what you don not need for what you want — with the option to add or receive a money difference.',
    'landing.getStarted': 'Get Started Free',
    'landing.signIn': 'Sign In',
    'landing.message': 'With Tebadel, money is optional — only when you need it.',

    // Features
    'landing.featuresTitle': 'Why Choose Tebadel?',
    'landing.featuresSubtitle': 'Experience the easiest and safest way to trade items — with optional cash difference when needed.',
    'landing.feature1.title': 'Trade Anything',
    'landing.feature1.description': 'Exchange items without direct selling — and add or receive a money difference if necessary.',
    'landing.feature2.title': 'Safe Community',
    'landing.feature2.description': 'Join a trusted community of traders with verified profiles and ratings.',
    'landing.feature3.title': 'Secure Trading',
    'landing.feature3.description': 'Protected transactions with built-in dispute resolution and support.',
    'landing.feature4.title': 'Instant Matching',
    'landing.feature4.description': 'Smart algorithm matches you with traders who want what you have.',

    // Services
    'landing.servicesTitle': 'Our Services',
    'landing.servicesSubtitle': 'Comprehensive trading solutions tailored for the modern Arabic marketplace',
    'landing.services.direct.title': 'Direct Item Exchange',
    'landing.services.direct.description': 'Trade items directly without any money involved. Perfect for equal value exchanges.',
    'landing.services.money.title': 'Money Difference Trading',
    'landing.services.money.description': 'Add or receive money to balance the trade when items have different values.',
    'landing.services.secure.title': 'Secure Transactions',
    'landing.services.secure.description': 'All trades are protected with our secure escrow system and dispute resolution.',
    'landing.services.community.title': 'Community Verification',
    'landing.services.community.description': 'User verification system ensures safe trading with trusted community members.',

    // Stats
    'landing.stats.traders': 'Active Traders',
    'landing.stats.items': 'Items Traded',
    'landing.stats.success': 'Success Rate',

    // Testimonials
    'landing.testimonialsTitle': 'What Our Users Say',
    'landing.testimonialsSubtitle': 'Real experiences from our trading community',
    'landing.testimonials.user1.name': 'Ahmed Al-Rashid',
    'landing.testimonials.user1.text': 'Tebadel made it so easy to trade my old laptop for a bicycle. The money difference feature was perfect!',
    'landing.testimonials.user2.name': 'Fatima Hassan',
    'landing.testimonials.user2.text': 'I love how safe and secure the platform is. Trading has never been this convenient.',
    'landing.testimonials.user3.name': 'Omar Mahmoud',
    'landing.testimonials.user3.text': 'The community is amazing and the customer support is excellent. Highly recommended!',

    // FAQ
    'landing.faqTitle': 'Frequently Asked Questions',
    'landing.faqSubtitle': 'Everything you need to know about trading on Tebadel',
    'landing.faq.q1.question': 'How does the money difference feature work?',
    'landing.faq.q1.answer': 'When trading items of different values, you can add or receive money to balance the trade. This makes fair exchanges possible for any items.',
    'landing.faq.q2.question': 'Is my personal information safe?',
    'landing.faq.q2.answer': 'Yes, we use advanced encryption and security measures to protect all user data. Your privacy is our top priority.',
    'landing.faq.q3.question': 'What if I have a dispute with another trader?',
    'landing.faq.q3.answer': 'We have a comprehensive dispute resolution system with dedicated support staff to help resolve any issues fairly.',
    'landing.faq.q4.question': 'Are there any fees for using Tebadel?',
    'landing.faq.q4.answer': 'Basic trading is free! We only charge a small fee for premium features and secure payment processing.',

    // Contact
    'landing.contactTitle': 'Get in Touch',
    'landing.contactSubtitle': 'We\'re here to help you with any questions or support you need',
    'landing.contact.phone': 'Phone Support',
    'landing.contact.email': 'Email Support',
    'landing.contact.support': 'Customer Support',
    'landing.contact.supportHours': '24/7 Available',
    'landing.contact.form.name': 'Full Name',
    'landing.contact.form.namePlaceholder': 'Enter your full name',
    'landing.contact.form.email': 'Email Address',
    'landing.contact.form.emailPlaceholder': 'Enter your email address',
    'landing.contact.form.message': 'Message',
    'landing.contact.form.messagePlaceholder': 'Tell us how we can help you...',
    'landing.contact.form.send': 'Send Message',

    // CTA
    'landing.ctaTitle': 'Ready to Start Trading?',
    'landing.ctaSubtitle': 'Join our community today and discover the joy of sustainable trading.',
    'landing.ctaButton': 'Create Your Account',

    // Items
    'items.title': 'Available Items',
    'items.search': 'Search items...',
    'items.category': 'Category',
    'items.allCategories': 'All Categories',
    'items.postNew': 'Post New Item',
    'items.myItems': 'My Items',
    'items.noItems': 'No items found',
    'items.status.available': 'Available',
    'items.status.inExchange': 'In Exchange',
    'items.status.exchanged': 'Exchanged',
    'items.image': 'Image',
    "myItems.yourItems": "Your items",
    'items.noImage': 'No image',
    'items.loadError': 'Failed to load items',
    'items.deleteSuccess': 'Item deleted successfully',


    // Trading & Money Difference
    'trade.makeOffer': 'Make Offer',
    'trade.moneyDifference': 'Money Difference',
    'trade.addMoney': 'Add Money',
    'trade.receiveMoney': 'Receive Money',
    'trade.amount': 'Amount',
    'trade.currency': 'Currency',
    'trade.offerDetails': 'Offer Details',
    'trade.yourItem': 'Your Item',
    'trade.theirItem': 'Their Item',
    'trade.moneyFromYou': 'Money from you',
    'trade.moneyToYou': 'Money to you',
    'trade.sendOffer': 'Send Offer',
    'trade.acceptOffer': 'Accept Offer',
    'trade.rejectOffer': 'Reject Offer',
    'trade.counterOffer': 'Counter Offer',
    'trade.negotiate': 'Negotiate',
    'trade.selectYourItem': 'Please select one of your items to offer',
    'trade.selectYourItemPlaceholder': 'Select your item...',
    'trade.moneyDifferencePlaceholder': 'Enter money difference (optional)',
    'trade.moneyDirection': 'Money Direction',
    'trade.moneyDirectionPlaceholder': 'Select money direction...',
    'trade.pay': 'Pay',
    'trade.receive': 'Receive',
    'trade.description': 'Description',
    'trade.descriptionPlaceholder': 'Enter a description for your offer (optional)',
    'trade.fillAllFields': 'Please fill all required fields',
    'trade.offerSent': 'Offer sent successfully!',

    // Common
    'common.loading': 'Loading...',
    'common.error': 'Something went wrong',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.view': 'View',
    'common.send': 'Send',
    'common.accept': 'Accept',
    'common.reject': 'Reject',
    'myItems.subtitle': 'Manage your items and track exchanges',
    'myItems.backToList': 'Back to List',
    'myItems.itemDetails': 'Item Details',

    // Exchange requests
    exchangeRequests: 'Exchange Requests',
    sentRequests: 'Sent Requests',
    receivedRequests: 'Received Requests',
    noExchangeRequests: 'No exchange requests found',
    exchangeRequestSent: 'Exchange request sent successfully',
    exchangeRequestAccepted: 'Exchange request accepted',
    exchangeRequestRejected: 'Exchange request rejected',
    exchangeRequestCanceled: 'Exchange request canceled',
    requestExchange: 'Request Exchange',
    acceptRequest: 'Accept',
    rejectRequest: 'Reject',
    cancelRequest: 'Cancel',
    pending: 'Pending',
    accepted: 'Accepted',
    rejected: 'Rejected',
    moneyDifference: 'Money Difference',
    optional: 'Optional',
    offeredItem: 'Offered Item',
    requestedItem: 'Requested Item',
    fromUser: 'From',
    toUser: 'To',
    exchangeRequestError: 'Failed to process exchange request',

    // Address management
    myAddresses: 'My Addresses',
    manageAddresses: 'Manage your saved addresses',
    addAddress: 'Add Address',
    editAddress: 'Edit Address',
    deleteAddress: 'Delete Address',
    deleteAddressConfirmation: 'Are you sure you want to delete this address? This action cannot be undone.',
    noAddresses: 'No addresses yet',
    noAddressesDescription: 'Add your first address to get started with deliveries and exchanges.',
    addFirstAddress: 'Add Your First Address',
    addressDetails: 'Address Details',
    street: 'Street Address',
    streetPlaceholder: 'Enter street address',
    city: 'City',
    cityPlaceholder: 'Enter city',
    state: 'State/Province',
    statePlaceholder: 'Enter state or province',
    zipCode: 'Zip/Postal Code',
    zipCodePlaceholder: 'Enter zip or postal code',
    country: 'Country',
    countryPlaceholder: 'Enter country',
    defaultAddress: 'Default Address',
    defaultAddressDescription: 'Use this as your primary address for deliveries',
    default: 'Default',
    confirmLocation: 'Confirm Location',
    latitude: 'Latitude',
    longitude: 'Longitude',
    latitudePlaceholder: 'Enter latitude',
    longitudePlaceholder: 'Enter longitude',
    useCurrentLocation: 'Use Current Location',
    locationObtained: 'Location obtained successfully',
    locationError: 'Unable to get your location',
    geolocationNotSupported: 'Geolocation is not supported by this browser',
    coordinatesRequired: 'Both latitude and longitude are required',
    locationConfirmed: 'Location confirmed successfully',
    locationConfirmFailed: 'Failed to confirm location',
    addressCreated: 'Address created successfully',
    addressUpdated: 'Address updated successfully',
    addressDeleted: 'Address deleted successfully',
    addressCreateFailed: 'Failed to create address',
    addressUpdateFailed: 'Failed to update address',
    addressDeleteFailed: 'Failed to delete address',
    addressesFetchFailed: 'Failed to fetch addresses',
    addressNotFound: 'Address not found',
    saving: 'Saving...',
    deleting: 'Deleting...',
    confirming: 'Confirming...',
    back: 'Back',
    success: 'Success',
    error: 'Error',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    confirm: 'Confirm',
    loading: 'Loading...',

    // Exchange translations
    'exchange.title': 'Exchange Requests',
    'exchange.subtitle': 'Manage your exchange requests',
    'exchange.manageRequests': 'Manage Exchange Requests',
    'exchange.refresh': 'Refresh',
    'exchange.received': 'Received',
    'exchange.sent': 'Sent',
    'exchange.sentRequest': 'Sent Request',
    'exchange.receivedRequest': 'Received Request',
    'exchange.yourItem': 'Your Item',
    'exchange.theirItem': 'Their Item',
    'exchange.moneyDifference': 'Money Difference',
    'exchange.from': 'From',
    'exchange.to': 'To',
    'exchange.accept': 'Accept',
    'exchange.reject': 'Reject',
    'exchange.cancel': 'Cancel',
    'exchange.status.pending': 'Pending',
    'exchange.status.accepted': 'Accepted',
    'exchange.status.rejected': 'Rejected',
    'exchange.success': 'Success',
    'exchange.error': 'Error',
    'exchange.fetchError': 'Failed to fetch exchange requests',
    'exchange.acceptSuccess': 'Exchange request accepted successfully',
    'exchange.acceptError': 'Failed to accept exchange request',
    'exchange.rejectSuccess': 'Exchange request rejected successfully',
    'exchange.rejectError': 'Failed to reject exchange request',
    'exchange.cancelSuccess': 'Exchange request cancelled successfully',
    'exchange.cancelError': 'Failed to cancel exchange request',
    'exchange.noReceivedRequests': 'No Received Requests',
    'exchange.noReceivedRequestsDesc': 'You have not received any exchange requests yet',
    'exchange.noSentRequests': 'No Sent Requests',
    'exchange.noSentRequestsDesc': 'You have not sent any exchange requests yet',
    'exchange.heroAlt': 'Exchange and trading',
    'myItems.category': 'Category',
    'myItems.owner': 'Owner',
    'myItems.description': 'Description',
    'myItems.preferredExchange': 'Preferred Exchange',
    'myItems.edit': 'Edit Item',
    'myItems.close': 'Close',
    // QR Code
    'myItems.showQr': 'Show QR Code',
    'myItems.hideQr': 'Hide QR Code',
    'myItems.qrLoading': 'Loading QR...',
    'myItems.qrError': 'Failed to load QR code',
    'myItems.qrAlt': 'Item QR code',
    // Item Image
    'itemImage.heading': 'Item Image',
    'itemImage.noImage': 'No image uploaded',
    'itemImage.selectImageError': 'Please select an image file',
    'itemImage.sizeError': 'Image size must be less than 5MB',
    'itemImage.authError': 'Authentication token not found',
    'itemImage.uploadSuccess': 'Image uploaded successfully',
    'itemImage.removeSuccess': 'Image removed successfully',
    'itemImage.uploadError': 'Failed to upload image',
    'itemImage.removeError': 'Failed to remove image',
    'itemImage.uploading': 'Uploading...',
    'itemImage.change': 'Change Image',
    'itemImage.upload': 'Upload Image',
    'items.editItem': 'Edit Item',
    'items.createNewItem': 'Create New Item',
    'items.titlePlaceholder': 'Enter item title',
    'items.subTitle': 'Browse and find items to trade with others',
    'items.lookingFor': 'Looking for:',
    'items.description': 'Description',
    'items.descriptionPlaceholder': 'Enter item description',
    'items.preferredExchangeNote': 'Preferred Exchange Note',
    'items.preferredExchangeNotePlaceholder': 'Enter your preferred exchange details',
    'items.categoryPlaceholder': 'Select a category',
    'items.saving': 'Saving...',
    'items.updateSuccess': 'Item updated successfully',
    'items.createSuccess': 'Item created successfully',
    'items.loadCategoriesError': 'Failed to load categories',
    'exchange.pending': 'Pending',
    'exchange.accepted': 'Accepted',
    'exchange.rejected': 'Rejected',
    'exchange.money': 'Money',
    'exchange.arrow': 'Exchange Arrow',
    'exchange.details': 'Details',
    'exchange.loading': 'Loading...',
    'exchange.noRequests': 'No exchange requests found',
    'exchange.userInfo': 'User Info',
    'exchange.action': 'Action',
    'exchange.fromUser': 'From',
    'exchange.toUser': 'To',
    'exchange.date': 'Date',
  },
  ar: {
    // Navigation
    'nav.home': 'الرئيسية',
    'nav.myItems': 'عناصري',
    'nav.offers': 'عروض التبادل',
    'nav.messages': 'الرسائل',
    'nav.profile': 'الملف الشخصي',
    'nav.admin': 'إدارة',
    'nav.login': 'تسجيل الدخول',
    'nav.register': 'إنشاء حساب',
    'nav.logout': 'تسجيل خروج',

    // Auth
    'auth.welcome': 'مرحباً بك في تبادل',
    'auth.subtitle': 'تبادل الأشياء مع أو بدون نقود',
    'auth.email': 'البريد الإلكتروني',
    'auth.phone': 'رقم الجوال',
    'auth.phoneHolder': 'ادخل رقم الجوال',
    'auth.password': 'كلمة المرور',
    'auth.passwordHandler': 'ادخل كلمة المرور',
    'auth.loginError': 'فشلت عملية تسجيل الدخول',
    'auth.loginSuccess': 'تم تسجيل الدخول بنجاح',
    'auth.name': 'الاسم الكامل',
    'auth.firstName': 'الإسم الأول',
    'auth.lastName': 'إسم العائلة',
    'auth.registerButton': 'إنشاء حساب',
    'auth.switchToRegister': 'ليس لديك حساب؟ سجل الآن',
    'auth.switchToLogin': 'لديك حساب؟ سجل دخولك',
    'auth.firstNameHolder': 'ادخل الاسم الأول',
    'auth.lastNameHolder': 'ادخل اسم العائلة',
    'auth.passwordHolder': 'ادخل كلمة المرور',
    'auth.loginButton': 'تسجيل الدخول',
    'auth.registerSuccess': 'تم إنشاء الحساب بنجاح!',
    'auth.registerError': 'فشل في إنشاء الحساب. حاول مرة أخرى.',

    // Landing Page
    'landing.badge': 'مستقبل التبادل',
    'landing.heroTitle': 'تبادل الأشياء،',
    'landing.heroTitleHighlight': ' مع دفع فارق عند الحاجة',
    'landing.heroSubtitle': 'منصة المقايضة الحديثة: بدّل ما لا تحتاجه، واحصل على ما تحب — مع إمكانية دفع أو استلام فرق نقدي.',
    'landing.getStarted': 'ابدأ مجاناً',
    'landing.signIn': 'تسجيل الدخول',
    'landing.message': 'في تبادل، لا حاجة للمال دائمًا — فقط عندما تحتاجه.',

    // Features
    'landing.featuresTitle': 'لماذا تختار تبادل؟',
    'landing.featuresSubtitle': 'اختبر أسهل وأأمن طريقة لتبادل الأشياء مع إمكانية دفع أو استلام فرق نقدي حسب الاتفاق.',
    'landing.feature1.title': 'تبادل أي شيء',
    'landing.feature1.description': 'تبادل الأشياء بدون بيع مباشر — ويمكنك دفع أو استلام فرق نقدي حسب رغبتك.',
    'landing.feature2.title': 'مجتمع آمن',
    'landing.feature2.description': 'انضم إلى مجتمع موثوق من التجار مع ملفات شخصية وتقييمات محققة.',
    'landing.feature3.title': 'تداول آمن',
    'landing.feature3.description': 'معاملات محمية مع حل النزاعات المدمج والدعم.',
    'landing.feature4.title': 'مطابقة فورية',
    'landing.feature4.description': 'خوارزمية ذكية تربطك بالتجار الذين يريدون ما لديك.',

    // Services
    'landing.servicesTitle': 'خدماتنا',
    'landing.servicesSubtitle': 'حلول تداول شاملة مصممة للسوق العربي الحديث',
    'landing.services.direct.title': 'تبادل مباشر للأشياء',
    'landing.services.direct.description': 'تبادل الأشياء مباشرة بدون تدخل المال. مثالي للتبادلات متساوية القيمة.',
    'landing.services.money.title': 'تداول بفرق مالي',
    'landing.services.money.description': 'أضف أو استلم مال لموازنة التبادل عندما تكون الأشياء بقيم مختلفة.',
    'landing.services.secure.title': 'معاملات آمنة',
    'landing.services.secure.description': 'جميع التبادلات محمية بنظام الضمان الآمن وحل النزاعات.',
    'landing.services.community.title': 'تحقق المجتمع',
    'landing.services.community.description': 'نظام تحقق المستخدمين يضمن التداول الآمن مع أعضاء مجتمع موثوقين.',

    // Stats
    'landing.stats.traders': 'تاجر نشط',
    'landing.stats.items': 'عنصر متبادل',
    'landing.stats.success': 'معدل النجاح',

    // Testimonials
    'landing.testimonialsTitle': 'ماذا يقول مستخدمونا',
    'landing.testimonialsSubtitle': 'تجارب حقيقية من مجتمع التداول لدينا',
    'landing.testimonials.user1.name': 'أحمد الراشد',
    'landing.testimonials.user1.text': 'تبادل جعل الأمر سهلاً جداً لتبديل لابتوبي القديم بدراجة هوائية. خاصية الفرق المالي كانت مثالية!',
    'landing.testimonials.user2.name': 'فاطمة حسن',
    'landing.testimonials.user2.text': 'أحب مدى أمان وحماية المنصة. التداول لم يكن بهذه السهولة من قبل.',
    'landing.testimonials.user3.name': 'عمر محمود',
    'landing.testimonials.user3.text': 'المجتمع رائع ودعم العملاء ممتاز. أنصح به بشدة!',

    // FAQ
    'landing.faqTitle': 'الأسئلة الشائعة',
    'landing.faqSubtitle': 'كل ما تحتاج معرفته عن التداول في تبادل',
    'landing.faq.q1.question': 'كيف تعمل خاصية الفرق المالي؟',
    'landing.faq.q1.answer': 'عند تبادل أشياء بقيم مختلفة، يمكنك إضافة أو استلام مال لموازنة التبادل. هذا يجعل التبادل العادل ممكناً لأي أشياء.',
    'landing.faq.q2.question': 'هل معلوماتي الشخصية آمنة؟',
    'landing.faq.q2.answer': 'نعم، نستخدم تشفير متقدم وإجراءات أمنية لحماية جميع بيانات المستخدمين. خصوصيتك هي أولويتنا القصوى.',
    'landing.faq.q3.question': 'ماذا لو كان لدي نزاع مع تاجر آخر؟',
    'landing.faq.q3.answer': 'لدينا نظام شامل لحل النزاعات مع فريق دعم مخصص لمساعدة حل أي مشاكل بعدالة.',
    'landing.faq.q4.question': 'هل هناك رسوم لاستخدام تبادل؟',
    'landing.faq.q4.answer': 'التداول الأساسي مجاني! نحن نتقاضى رسوم صغيرة فقط للميزات المتميزة ومعالجة الدفع الآمن.',

    // Contact
    'landing.contactTitle': 'تواصل معنا',
    'landing.contactSubtitle': 'نحن هنا لمساعدتك في أي أسئلة أو دعم تحتاجه',
    'landing.contact.phone': 'الدعم الهاتفي',
    'landing.contact.email': 'الدعم بالبريد الإلكتروني',
    'landing.contact.support': 'دعم العملاء',
    'landing.contact.supportHours': 'متاح ٢٤/٧',
    'landing.contact.form.name': 'الاسم الكامل',
    'landing.contact.form.namePlaceholder': 'ادخل اسمك الكامل',
    'landing.contact.form.email': 'البريد الإلكتروني',
    'landing.contact.form.emailPlaceholder': 'ادخل بريدك الإلكتروني',
    'landing.contact.form.message': 'الرسالة',
    'landing.contact.form.messagePlaceholder': 'أخبرنا كيف يمكننا مساعدتك...',
    'landing.contact.form.send': 'إرسال الرسالة',

    // CTA
    'landing.ctaTitle': 'مستعد لبدء التداول؟',
    'landing.ctaSubtitle': 'انضم إلى مجتمعنا اليوم واكتشف متعة التداول المستدام.',
    'landing.ctaButton': 'أنشئ حسابك',

    // Items
    'items.title': 'الأغراض المتاحة',
    'items.search': 'البحث عن أغراض...',
    'items.category': 'الفئة',
    'items.allCategories': 'جميع الفئات',
    'items.postNew': 'نشر غرض جديد',
    'items.myItems': 'أغراضي',
    'items.noItems': 'لم يتم العثور على أغراض',
    'items.status.available': 'متاح',
    'items.status.inExchange': 'قيد التبديل',
    'items.status.exchanged': 'تم التبديل',
    'items.image': 'صورة',
    'items.noImage': 'لا توجد صورة',
    'items.loadError': 'فشل في تحميل الأغراض',
    'items.deleteSuccess': 'تم حذف الغرض بنجاح',
    'items.subTitle': 'تصفح وابحث عن أغراض للتبادل مع الآخرين',
    'items.lookingFor': 'يبحث عن:',
    "myItems.yourItems": "أغراضك",
    "myItems.deleteConfirm": "تأكيد حذف الغرض",
    "myItems.itemDetails": "تفاصيل الغرض",
    "myItems.backToList": "العودة إلى القائمة",
    'myItems.category': 'الفئة',
    'myItems.owner': 'المالك',
    'myItems.description': 'الوصف',
    'myItems.preferredExchange': 'التبادل المفضل',
    'myItems.edit': 'تعديل الغرض',
    'myItems.close': 'إغلاق',
    // QR Code
    'myItems.showQr': 'عرض رمز الاستجابة السريعة',
    'myItems.hideQr': 'إخفاء رمز الاستجابة السريعة',
    'myItems.qrLoading': 'جاري تحميل الرمز...',
    'myItems.qrError': 'فشل في تحميل رمز الاستجابة السريعة',
    'myItems.qrAlt': 'رمز الاستجابة السريعة للغرض',
    // Trading & Money Difference
    'trade.makeOffer': 'تقديم عرض',
    'trade.moneyDifference': 'فرق المال',
    'trade.addMoney': 'إضافة مال',
    'trade.receiveMoney': 'استلام مال',
    'trade.amount': 'المبلغ',
    'trade.currency': 'العملة',
    'trade.offerDetails': 'تفاصيل العرض',
    'trade.yourItem': 'غرضك',
    'trade.theirItem': 'غرضه',
    'trade.moneyFromYou': 'مال منك',
    'trade.moneyToYou': 'مال إليك',
    'trade.sendOffer': 'إرسال العرض',
    'trade.acceptOffer': 'قبول العرض',
    'trade.rejectOffer': 'رفض العرض',
    'trade.counterOffer': 'عرض مضاد',
    'trade.negotiate': 'تفاوض',
    'trade.selectYourItem': 'يرجى اختيار أحد أغراضك لتقديمه',
    'trade.selectYourItemPlaceholder': 'اختر غرضك...',
    'trade.moneyDifferencePlaceholder': 'أدخل فرق المال (اختياري)',
    'trade.moneyDirection': 'اتجاه المال',
    'trade.moneyDirectionPlaceholder': 'اختر اتجاه المال...',
    'trade.pay': 'أريد دفع فرق المال ',
    'trade.receive': 'أريد استلام فرق المال ',
    'trade.description': 'الوصف',
    'trade.descriptionPlaceholder': 'أدخل وصفًا لعرضك (اختياري)',
    'trade.fillAllFields': 'يرجى تعبئة جميع الحقول المطلوبة',
    'trade.offerSent': 'تم إرسال العرض بنجاح!',

    // Common
    'common.loading': 'جاري التحميل...',
    'common.error': 'حدث خطأ ما',
    'common.save': 'حفظ',
    'common.cancel': 'إلغاء',
    'common.delete': 'حذف',
    'common.edit': 'تعديل',
    'common.view': 'عرض',
    'common.send': 'إرسال',
    'common.accept': 'قبول',
    'common.reject': 'رفض',
    'myItems.subtitle': 'إدارة عناصرك وتتبع التبادلات',

    // Item Image
    'itemImage.heading': 'صورة العنصر',
    'itemImage.noImage': 'لم يتم تحميل صورة',
    'itemImage.selectImageError': 'يرجى اختيار ملف صورة',
    'itemImage.sizeError': 'يجب أن يكون حجم الصورة أقل من 5 ميجابايت',
    'itemImage.authError': 'رمز المصادقة غير موجود',
    'itemImage.uploadSuccess': 'تم تحميل الصورة بنجاح',
    'itemImage.removeSuccess': 'تم حذف الصورة بنجاح',
    'itemImage.uploadError': 'فشل في تحميل الصورة',
    'itemImage.removeError': 'فشل في حذف الصورة',
    'itemImage.uploading': 'جاري التحميل...',
    'itemImage.change': 'تغيير الصورة',
    'itemImage.upload': 'تحميل صورة',
    'items.editItem': 'تعديل العنصر',
    'items.createNewItem': 'إنشاء عنصر جديد',
    'items.titlePlaceholder': 'ادخل عنوان العنصر',
    'items.description': 'الوصف',
    'items.descriptionPlaceholder': 'ادخل وصف العنصر',
    'items.preferredExchangeNote': 'ملاحظة التبادل المفضل',
    'items.preferredExchangeNotePlaceholder': 'ادخل تفاصيل التبادل المفضل',
    'items.categoryPlaceholder': 'اختر فئة',
    'items.saving': 'جاري الحفظ...',
    'items.updateSuccess': 'تم تحديث العنصر بنجاح',
    'items.createSuccess': 'تم إنشاء العنصر بنجاح',
    'items.loadCategoriesError': 'فشل في تحميل الفئات',
    'exchange.receivedRequest' : 'الطلبات الواردة',
    'exchange.pending': 'قيد الانتظار',
    'exchange.accepted': 'تم القبول',
    'exchange.rejected': 'مرفوض',
    'exchange.money': 'مال',
    'exchange.arrow': 'سهم التبادل',
    'exchange.details': 'تفاصيل',
    'exchange.loading': 'جاري التحميل...',
    'exchange.noRequests': 'لا توجد طلبات تبادل',
    'exchange.noSentRequests': 'لا توجد طلبات مرسلة',
    'exchange.noReceivedRequests': 'لا توجد طلبات مستلمة',
    'exchange.userInfo': 'معلومات المستخدم',
    'exchange.action': 'إجراء',
    'exchange.fromUser': 'من',
    'exchange.toUser': 'إلى',
    'exchange.date': 'التاريخ',
    'exchange.heroAlt': 'التبادل والتجارة',
    'exchange.title': 'طلبات التبادل',
    'exchange.subtitle': 'إدارة طلبات التبادل الخاصة بك',
    'exchange.manageRequests': 'إدارة طلبات التبادل',
    'exchange.received': 'الواردة',
    'exchange.sent': 'المرسلة',
    'exchange.sentRequest': 'طلب مرسل',
    'exchange.noReceivedRequestsDesc': 'لم تستلم أي طلبات تبادل بعد',
    'exchange.refresh': 'تحديث',
    'exchange.status.pending': 'قيد الانتظار',
    'exchange.yourItem': 'عنصرك',
    'exchange.theirItem': 'عنصرهم',
    'exchange.moneyDifference': 'فرق المال',
    'exchange.from': 'من',
    'exchange.to': 'إلى',
    'exchange.cancel': 'إلغاء',
    'exchange.status.cancelled': 'ملغي',
    'exchange.accept' : 'قبول',
    'exchange.reject' :'رفض',
    'exchange.status.accepted' :'تمت الموافقة',

    // Exchange requests
    exchangeRequests: 'طلبات التبادل',
    sentRequests: 'الطلبات المرسلة',
    receivedRequests: 'الطلبات المستلمة',
    noExchangeRequests: 'لا توجد طلبات تبادل',
    exchangeRequestSent: 'تم إرسال طلب التبادل بنجاح',
    exchangeRequestAccepted: 'تم قبول طلب التبادل',
    exchangeRequestRejected: 'تم رفض طلب التبادل',
    exchangeRequestCanceled: 'تم إلغاء طلب التبادل',
    requestExchange: 'طلب تبادل',
    acceptRequest: 'قبول',
    rejectRequest: 'رفض',
    cancelRequest: 'إلغاء',
    pending: 'في الانتظار',
    accepted: 'مقبول',
    rejected: 'مرفوض',
    moneyDifference: 'الفرق المالي',
    optional: 'اختياري',
    offeredItem: 'العنصر المعروض',
    requestedItem: 'العنصر المطلوب',
    fromUser: 'من',
    toUser: 'إلى',
    exchangeRequestError: 'فشل في معالجة طلب التبادل',

    // Address management
    myAddresses: 'عناويني',
    manageAddresses: 'إدارة العناوين المحفوظة',
    addAddress: 'إضافة عنوان',
    editAddress: 'تعديل العنوان',
    deleteAddress: 'حذف العنوان',
    deleteAddressConfirmation: 'هل أنت متأكد من حذف هذا العنوان؟ لا يمكن التراجع عن هذا الإجراء.',
    noAddresses: 'لا توجد عناوين حتى الآن',
    noAddressesDescription: 'أضف عنوانك الأول للبدء في التوصيل والتبادل.',
    addFirstAddress: 'أضف عنوانك الأول',
    addressDetails: 'تفاصيل العنوان',
    street: 'عنوان الشارع',
    streetPlaceholder: 'أدخل عنوان الشارع',
    city: 'المدينة',
    cityPlaceholder: 'أدخل المدينة',
    state: 'الولاية/المحافظة',
    statePlaceholder: 'أدخل الولاية أو المحافظة',
    zipCode: 'الرمز البريدي',
    zipCodePlaceholder: 'أدخل الرمز البريدي',
    country: 'البلد',
    countryPlaceholder: 'أدخل البلد',
    defaultAddress: 'العنوان الافتراضي',
    defaultAddressDescription: 'استخدم هذا كعنوانك الأساسي للتوصيل',
    default: 'افتراضي',
    confirmLocation: 'تأكيد الموقع',
    latitude: 'خط العرض',
    longitude: 'خط الطول',
    latitudePlaceholder: 'أدخل خط العرض',
    longitudePlaceholder: 'أدخل خط الطول',
    useCurrentLocation: 'استخدم الموقع الحالي',
    locationObtained: 'تم الحصول على الموقع بنجاح',
    locationError: 'تعذر الحصول على موقعك',
    geolocationNotSupported: 'تحديد الموقع الجغرافي غير مدعوم في هذا المتصفح',
    coordinatesRequired: 'خط العرض وخط الطول مطلوبان',
    locationConfirmed: 'تم تأكيد الموقع بنجاح',
    locationConfirmFailed: 'فشل في تأكيد الموقع',
    addressCreated: 'تم إنشاء العنوان بنجاح',
    addressUpdated: 'تم تحديث العنوان بنجاح',
    addressDeleted: 'تم حذف العنوان بنجاح',
    addressCreateFailed: 'فشل في إنشاء العنوان',
    addressUpdateFailed: 'فشل في تحديث العنوان',
    addressDeleteFailed: 'فشل في حذف العنوان',
    addressesFetchFailed: 'فشل في جلب العناوين',
    addressNotFound: 'العنوان غير موجود',
    saving: 'جاري الحفظ...',
    deleting: 'جاري الحذف...',
    confirming: 'جاري التأكيد...',
    back: 'رجوع',
    success: 'نجح',
    error: 'خطأ',
    save: 'حفظ',
    cancel: 'إلغاء',
    delete: 'حذف',
    confirm: 'تأكيد',
    loading: 'جاري التحميل...',
  },
};

const LanguageContext = createContext<LanguageContextType | null>(null);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<'en' | 'ar'>(() => {
    const saved = localStorage.getItem('language');
    return (saved as 'en' | 'ar') || 'ar';
  });

  const setLanguage = (lang: 'en' | 'ar') => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
    document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = lang;
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['en']] || key;
  };

  useEffect(() => {
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language]);

  return (
    <LanguageContext.Provider value={{
      language,
      setLanguage,
      t,
      isRTL: language === 'ar',
    }}>
      {children}
    </LanguageContext.Provider>
  );
};
